### ISSUE TITLE
feat: `b3lbctl init tenant` command

### ISSUE THREAD

**Issue by SLedunois** [SLedunois/b3lbctl#42]
## Command
`b3lbctl init tenant`
## Flags
- `-hn`, `--hostname` (Required) tenant hostname.
- `-d`, `--destination` file creation destination. Default is `$HOME/.b3lb`
## Description
Based on hostname flag, it creates a new tenant file named `<hostname>.tenant.yml` (ex `localhost.tenant.yml`) in `$HOME/.b3lb` sing the following content:
```yaml
kind: Tenant
spec:
  host: <hostname>
instances:
```
