### ISSUE TITLE
feat: `b3lbctl describe tenant <tenant>`

### ISSUE THREAD

**Issue by SLedunois** [SLedunois/b3lbctl#43]
## Command
`b3lbctl describe tenant <tenant>`
## Flags
No flags
## Description
It calls `GET /admin/api/tenants/:hostname` endpoint to retrieve a given tenant and print the yaml content like:
```yaml
kind: Tenant
spec:
  host: balancer.tenant1.com
instances:
  - http://bigbluebutton1
  - http://bigbluebutton2
  - http://bigbluebutton3
```
